CREATE TABLE IF NOT EXISTS captives_data (
            volume INTEGER NOT NULL,
            id VARCHAR(15) PRIMARY KEY NOT NULL, 
            name TEXT,
            sex VARCHAR(4), 
            height INTEGER, 
            build VARCHAR(4), 
            dentition VARCHAR(4), 
            special_peculiarities TEXT, 
            date_of_birth DATE, 
            place_of_birth VARCHAR(100), 
            place_of_residence VARCHAR(100), 
            residence VARCHAR(100), 
            religion VARCHAR(4), 
            childhood_status VARCHAR(4), 
            marital_status VARCHAR(50), 
            number_of_children INTEGER, 
            occupation VARCHAR(100), 
            occupation_2 VARCHAR(100), 
            occupation_3 VARCHAR(100), 
            military_service VARCHAR(100), 
            literacy VARCHAR(50),  
            education VARCHAR(50), 
            criminal_history VARCHAR(500), 
            crime VARCHAR(150), 
            sentence_begins DATE, 
            sentence_expires DATE, 
            prison_term_day INTEGER, 
            ransome INTEGER, 
            associates VARCHAR(200), 
            degree_of_crime VARCHAR(100), 
            degree_of_punishment VARCHAR(100), 
            notes VARCHAR(400),
            arrest_site VARCHAR(100), 
            username VARCHAR(50) Not Null,
            record_session SERIAL NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );